<a href="https://colab.research.google.com/github/bgorume/greends-fads-first-project/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("vikasukani/forest-firearea-datasets")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/vikasukani/forest-firearea-datasets?dataset_version_number=1...

100%|██████████| 7.10k/7.10k [00:00<00:00, 9.62MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/vikasukani/forest-firearea-datasets/versions/1

In [5]:
import pandas as pd

In [6]:
import os

In [9]:
file_path=os.path.join(path,"forestfires.csv")
df=pd.read_csv(file_path)
display(df)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [12]:
print(df)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [14]:
df.columns.to_list()

['X',
 'Y',
 'month',
 'day',
 'FFMC',
 'DMC',
 'DC',
 'ISI',
 'temp',
 'RH',
 'wind',
 'rain',
 'area']

In [16]:
df['temp']

0       8.2
1      18.0
2      14.6
3       8.3
4      11.4
       ...
512    27.8
513    21.9
514    21.2
515    25.6
516    11.8
Name: temp, Length: 517, dtype: float64

In [17]:
# Filter for fires where the temperature is higher than 25
fires_temp_above_25 = df[df['temp'] > 25]
display(fires_temp_above_25)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0  0.00
28   6  3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   0.0  0.00
30   6  3   sep  fri  94.3   85.1  692.3  15.9  25.4  24   3.6   0.0  0.00
45   5  6   sep  wed  94.3   85.1  692.3  15.9  25.9  24   4.0   0.0  0.00
55   4  3   sep  thu  92.9  137.0  706.4   9.2  27.7  24   2.2   0.0  0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...   ...
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0  0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0  0.00
511  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0  0.00
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  6.44
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  0.00

[65 rows x 13 columns]

In [18]:
# Filter for fires where the temperature is higher than 25 and between 20 and 30 (inclusive of 30)
fires_temp_25_to_30 = df[(df['temp'] > 25) & (df['temp'] <= 30)]
display(fires_temp_25_to_30)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain     area
14   6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0     0.00
30   6  3   sep  fri  94.3   85.1  692.3  15.9  25.4  24   3.6   0.0     0.00
45   5  6   sep  wed  94.3   85.1  692.3  15.9  25.9  24   4.0   0.0     0.00
55   4  3   sep  thu  92.9  137.0  706.4   9.2  27.7  24   2.2   0.0     0.00
74   5  4   sep  fri  93.3  141.2  713.9  13.9  27.6  30   1.3   0.0     0.00
86   1  2   sep  thu  92.9  137.0  706.4   9.2  25.4  27   2.2   0.0     0.00
88   1  2   sep  sun  93.5  149.3  728.6   8.1  25.3  36   3.6   0.0     0.00
145  6  5   aug  thu  95.2  131.7  578.8  10.4  27.4  22   4.0   0.0     0.90
154  1  5   sep  sat  93.4  145.4  721.4   8.1  29.6  27   2.7   0.0     1.46
156  2  4   sep  sat  93.4  145.4  721.4   8.1  28.6  27   2.2   0.0     1.61
228  4  6   sep  sun  93.5  149.3  728.6   8.1  28.3  26   3.1   0.0    64.10
230  4  4   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0    88.49
231  1  5   sep  sun  93.5  149.3  728.6   8.1  27.8  27   3.1   0.0    95.18
238  6  5   sep  sat  92.5  121.1  674.4   8.6  25.1  27   4.0   0.0  1090.84
245  3  4   aug  sun  91.8  175.1  700.7  13.8  26.8  38   6.3   0.0     0.76
246  5  4   aug  sun  91.8  175.1  700.7  13.8  25.7  39   5.4   0.0     0.09
248  8  6   aug  wed  93.1  157.3  666.7  13.5  28.7  28   2.7   0.0     0.00
250  8  5   aug  wed  93.1  157.3  666.7  13.5  26.8  25   3.1   0.0     0.68
260  2  4   aug  mon  93.6   97.9  542.0  14.4  28.3  32   4.0   0.0     8.85
291  9  4   jul  sat  91.6  104.2  474.9   9.0  25.3  39   0.9   0.0     8.00
293  7  6   jul  tue  93.1  180.4  430.8  11.0  26.9  28   5.4   0.0    86.45
310  7  4   sep  sun  92.4  105.8  758.1   9.9  25.3  27   2.7   0.0     0.00
382  8  6   aug  wed  95.2  217.7  690.0  18.0  28.2  29   1.8   0.0     5.86
398  1  2   aug  sat  93.7  231.1  715.1   8.4  25.9  32   3.1   0.0     0.00
399  9  5   jun  wed  93.3   49.5  297.7  14.0  28.0  34   4.5   0.0     0.00
400  9  5   jun  wed  93.3   49.5  297.7  14.0  28.0  34   4.5   0.0     8.16
405  2  2   aug  tue  94.6  212.1  680.9   9.5  27.9  27   2.2   0.0     0.00
413  7  5   aug  sat  93.7  231.1  715.1   8.4  26.4  33   3.6   0.0     0.00
415  8  6   aug  thu  94.8  222.4  698.6  13.9  27.5  27   4.9   0.0   746.28
416  6  3   jul  tue  92.7  164.1  575.8   8.9  26.3  39   3.1   0.0     7.02
420  8  8   aug  wed  91.7  191.4  635.9   7.8  26.2  36   4.5   0.0   185.76
422  8  6   jul  sun  88.9  263.1  795.9   5.2  29.3  27   3.6   0.0     6.30
424  8  6   aug  sat  93.7  231.1  715.1   8.4  26.9  31   3.6   0.0     4.96
427  2  4   aug  mon  92.1  207.0  672.6   8.2  27.9  33   2.2   0.0     2.35
428  1  3   aug  thu  94.8  222.4  698.6  13.9  26.2  34   5.8   0.0     0.00
436  8  6   aug  mon  92.1  207.0  672.6   8.2  26.8  35   1.3   0.0     0.54
441  8  6   aug  mon  92.1  207.0  672.6   8.2  25.5  29   1.8   0.0     1.23
474  4  3   jun  thu  93.0  103.8  316.7  10.8  26.4  35   2.7   0.0    10.08
476  4  3   jul  thu  93.5   85.3  395.0   9.9  27.2  28   1.3   0.0     1.76
477  4  3   jul  sun  93.7  101.3  423.4  14.7  26.1  45   4.0   0.0     7.36
487  5  4   aug  tue  95.1  141.3  605.8  17.7  26.4  34   3.6   0.0    16.40
490  4  4   aug  wed  95.1  141.3  605.8  17.7  28.7  33   4.0   0.0     0.00
493  1  3   aug  fri  95.9  158.0  633.6  11.3  27.5  29   4.5   0.0    43.32
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4    10.82
503  2  4   aug  wed  94.5  139.4  689.1  20.0  29.2  30   4.9   0.0     1.95
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0    49.59
505  1  2   aug  thu  91.0  163.2  744.4  10.1  26.7  35   1.8   0.0     5.80
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0     0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0     0.00
511  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0     0.00
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0     6.44
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0     0.00

In [22]:
df['month']

0      mar
1      oct
2      oct
3      mar
4      mar
      ...
512    aug
513    aug
514    aug
515    aug
516    nov
Name: month, Length: 517, dtype: object

In [23]:
import pandas as pd

# Assuming 'months' list already exists from previous execution
# If not, it can be defined as:
months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
]

# Create the 'mth' column with 3-letter lowercase abbreviations
mth_abbreviations = [month[:3].lower() for month in months]

# Create the new DataFrame
month_df = pd.DataFrame({
    'mth': mth_abbreviations,
    'Month': months
})

display(month_df)

    mth      Month
0   jan    January
1   feb   February
2   mar      March
3   apr      April
4   may        May
5   jun       June
6   jul       July
7   aug     August
8   sep  September
9   oct    October
10  nov   November
11  dec   December

In [26]:
merged_df = pd.merge(df, month_df, left_on='month', right_on='mth', how='left')
merged_df.drop(columns='mth', inplace=True)
display(merged_df)

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,Month
0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,March
1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.00,October
2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.00,October
3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.00,March
4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.00,March
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,4,3,aug,sun,81.6,56.7,665.6,1.9,27.8,32,2.7,0.0,6.44,August
513,2,4,aug,sun,81.6,56.7,665.6,1.9,21.9,71,5.8,0.0,54.29,August
514,7,4,aug,sun,81.6,56.7,665.6,1.9,21.2,70,6.7,0.0,11.16,August
515,1,4,aug,sat,94.4,146.0,614.7,11.3,25.6,42,4.0,0.0,0.00,August
516,6,3,nov,tue,79.5,3.0,106.7,1.1,11.8,31,4.5,0.0,0.00,November

In [31]:
firesbymonth = monthly_summary
display(firesbymonth)

        Month   avg_temp     avg_RH  fire_count
0       April  12.044444  46.888889           9
1      August  21.631522  45.489130         184
2    December   4.522222  38.444444           9
3    February   9.635000  55.700000          20
4     January   5.250000  89.000000           2
5        July  22.109375  45.125000          32
6        June  20.494118  45.117647          17
7       March  13.083333  40.000000          54
8         May  14.650000  67.000000           2
9    November  11.800000  31.000000           1
10    October  17.093333  37.466667          15
11  September  19.612209  42.843023         172